import type { Ledger, Movement, Purchase, Settings } from '@/lib/types';

/** The workbook's demonstration data, verbatim. */
export const settings: Settings = {
  company_name: 'DEMO COMPANY',
  store_name: 'SHARED GAS STORE',
  custodian: 'DEMO CUSTODIAN',
  currency_code: 'AED',
  posting_decimals: 2,
  rounding: 'NEAREST',
  fy_start_month: 1,
  report_month: '2026-09-01',
  history_start: '2026-07-01',
  lock_date: null,
  purchase_vat_rate: 0.05,
  purchase_includes_vat: false,
  backcharge_vat_rate: 0,
  backcharge_uplift: 0,
  valuation: 'FIFO_MONTHLY',
  honour_po_link: true,
  trigger_rule: 'ON_ISSUE_MONTH_END',
  delivery_allocation: 'PER_CYLINDER',
  purchasing_department: 'BAF',
  require_cost_code: true,
  require_receiver: true,
  allow_negative_stock: false,
  max_backdating_days: 7,
  empty_state_policy: 'ASSUME_ALL_OUT',
  posting_account: '5100-GAS',
  tolerance: 0.005,
  stock_unit: 'cyl',
  store_code: 'STORE',
  supplier_code: 'SUPPLIER',
  loss_code: 'LOSS',
};

const purchase = (
  n: number, poDate: string, poNo: string, dept: string, item: string,
  qty: number, rate: number,
): Purchase => ({
  id: `pu-${n}`,
  transaction_id: `P-${String(n).padStart(6, '0')}`,
  po_date: poDate,
  po_no: poNo,
  po_line: 1,
  vendor_no: 'DEMO-V1',
  purchasing_department: dept,
  item_code: item,
  qty_ordered: qty,
  unit_refill_rate: rate,
  delivery_charge: 0,
  other_charges: 0,
  qty_received: qty,
  receipt_date: poDate,
  received_by: `${dept} Receiver`,
  remarks: 'DEMONSTRATION ONLY',
  entered_by: 'BAF Receiver',
  entry_date: `${poDate}T00:00:00Z`,
});

export const purchases: Purchase[] = [
  purchase(1, '2026-07-01', 'DEMO-PO1', 'BAF', 'DEMO-O2', 10, 250),
  purchase(2, '2026-08-01', 'DEMO-PO2', 'BAA', 'DEMO-O2', 10, 280),
  purchase(3, '2026-09-01', 'DEMO-PO3', 'BAF', 'DEMO-O2', 10, 300),
  purchase(4, '2026-09-01', 'DEMO-PO4', 'BAF', 'DEMO-AC', 10, 250),
  purchase(5, '2026-09-01', 'DEMO-PO5', 'BAF', 'DEMO-AR', 20, 250),
  purchase(6, '2026-09-01', 'DEMO-PO6', 'BAA', 'DEMO-AR', 10, 280),
  purchase(7, '2026-09-01', 'DEMO-PO7', 'BAF', 'DEMO-CO2', 10, 250),
  purchase(8, '2026-09-01', 'DEMO-PO8', 'BAF', 'DEMO-MIX', 10, 250),
  purchase(9, '2026-09-01', 'DEMO-PO9', 'BAF', 'DEMO-N2', 10, 250),
];

const move = (
  n: number, date: string, kind: Movement['kind'], item: string, qty: number,
  from: string, to: string,
  extra: Partial<Movement> = {},
): Movement => ({
  id: `mv-${n}`,
  transaction_id: `M-${String(n).padStart(6, '0')}`,
  moved_on: date,
  kind,
  item_code: item,
  quantity: qty,
  from_code: from,
  to_code: to,
  receiver_name: to === 'STORE' || to === 'SUPPLIER' || to === 'LOSS' ? `${from} Receiver` : `${to} Receiver`,
  cost_code: null,
  location_area: null,
  source_po_line: null,
  residual_pct: null,
  reason: null,
  original_transaction_id: null,
  remarks: 'DEMONSTRATION ONLY',
  entry_timestamp: `${date}T00:00:00Z`,
  entered_by: 'BAF Receiver',
  ...extra,
});

export const movements: Movement[] = [
  move(1, '2026-07-02', 'ISSUE', 'DEMO-O2', 5, 'STORE', 'WOR', { cost_code: 'DEMO-WOR' }),
  move(2, '2026-07-04', 'RETURN_EMPTY', 'DEMO-O2', 3, 'WOR', 'STORE', { cost_code: 'DEMO-WOR', residual_pct: 0, original_transaction_id: 'M-000001' }),
  move(3, '2026-07-05', 'TO_SUPPLIER', 'DEMO-O2', 2, 'STORE', 'SUPPLIER', { receiver_name: null }),
  move(4, '2026-08-02', 'ISSUE', 'DEMO-O2', 10, 'STORE', 'WOR', { cost_code: 'DEMO-WOR' }),
  move(5, '2026-09-02', 'ISSUE', 'DEMO-O2', 4, 'STORE', 'BAF', { cost_code: 'DEMO-BAF' }),
  move(6, '2026-09-03', 'TRANSFER', 'DEMO-O2', 2, 'BAF', 'WOR', { cost_code: 'DEMO-WOR', original_transaction_id: 'M-000005' }),
  move(7, '2026-09-03', 'ISSUE', 'DEMO-O2', 2, 'STORE', 'BAA', { cost_code: 'DEMO-BAA', source_po_line: 'DEMO-PO3/1' }),
  move(8, '2026-09-04', 'ADJUSTMENT', 'DEMO-O2', 1, 'WOR', 'LOSS', { cost_code: 'DEMO-WOR', reason: 'Lost cylinder shell; gas already charged', original_transaction_id: 'M-000004' }),
  move(9, '2026-09-02', 'ISSUE', 'DEMO-AC', 5, 'STORE', 'WOR', { cost_code: 'DEMO-WOR' }),
  move(10, '2026-09-02', 'ISSUE', 'DEMO-AC', 3, 'STORE', 'BAA', { cost_code: 'DEMO-BAA' }),
  move(11, '2026-09-02', 'ISSUE', 'DEMO-AC', 2, 'STORE', 'BAF', { cost_code: 'DEMO-BAF' }),
  move(12, '2026-09-02', 'ISSUE', 'DEMO-CO2', 10, 'STORE', 'WOR', { cost_code: 'DEMO-WOR' }),
  move(13, '2026-09-04', 'RETURN_EMPTY', 'DEMO-CO2', 6, 'WOR', 'STORE', { cost_code: 'DEMO-WOR', residual_pct: 0, original_transaction_id: 'M-000012' }),
  move(14, '2026-09-05', 'TO_SUPPLIER', 'DEMO-CO2', 4, 'STORE', 'SUPPLIER', { receiver_name: null }),
  move(15, '2026-09-02', 'ISSUE', 'DEMO-MIX', 3, 'STORE', 'WOR', { cost_code: 'DEMO-WOR', source_po_line: 'DEMO-PO8/1' }),
  move(16, '2026-09-03', 'RETURN_UNUSED', 'DEMO-MIX', 1, 'WOR', 'STORE', { cost_code: 'DEMO-WOR', source_po_line: 'DEMO-PO8/1', original_transaction_id: 'M-000015' }),
  move(17, '2026-09-03', 'ISSUE', 'DEMO-N2', 2, 'STORE', 'BAF', { cost_code: 'DEMO-BAF' }),
];

export function demoLedger(overrides: Partial<Settings> = {}): Ledger {
  return {
    settings: { ...settings, ...overrides },
    departments: [
      { code: 'BAF', full_name: 'Fabrication', cost_centre: 'CC-BAF', contact: null, active: true, sort_order: 1 },
      { code: 'WOR', full_name: 'Workshop', cost_centre: 'CC-WOR', contact: null, active: true, sort_order: 2 },
      { code: 'BAA', full_name: 'Department BAA', cost_centre: 'CC-BAA', contact: null, active: true, sort_order: 3 },
    ],
    items: ['DEMO-O2', 'DEMO-AC', 'DEMO-AR', 'DEMO-CO2', 'DEMO-MIX', 'DEMO-N2'].map((code, i) => ({
      item_code: code,
      description: `${code} refill`,
      gas_type: null,
      cylinder_size: null,
      unit: 'cyl',
      nominal_content: null,
      standard_rate: 250,
      hazard_class: null,
      active: true,
      reorder_point: 2,
      minimum_stock: 1,
      max_dept_holding: 25,
      sort_order: i + 1,
    })),
    costCodes: [
      { code: 'DEMO-BAF', description: 'BAF job', owning_department: 'BAF', active: true },
      { code: 'DEMO-WOR', description: 'WOR job', owning_department: 'WOR', active: true },
      { code: 'DEMO-BAA', description: 'BAA job', owning_department: 'BAA', active: true },
    ],
    personnel: [
      { employee_no: 'DEMO-E1', name: 'BAF Receiver', department: 'BAF', active: true },
      { employee_no: 'DEMO-E2', name: 'WOR Receiver', department: 'WOR', active: true },
      { employee_no: 'DEMO-E3', name: 'BAA Receiver', department: 'BAA', active: true },
    ],
    suppliers: [{ vendor_no: 'DEMO-V1', name: 'Demonstration supplier', contact: null, active: true }],
    purchases,
    movements,
  };
}
